# [ LOCAL DEFAULTS ]
## For your convenience, only change the default_cargoport_directory using the -setup flag
default_cargoport_directory: /var/cargoport
default_output_directory: /var/cargoport/local

## Skip all local backups from this machine by default, requires remote flags
skip_local_backups: false

# [ REMOTE TRANSFER DEFAULTS]
default_remote_user: admin
default_remote_host: 10.0.0.1

# If cargoport is also set up on the remote target machine(s), you may want to use this!
#   Otherwise use the default ~/ output
#default_remote_output_dir: /var/cargoport/remote
default_remote_output_dir: ~/

# [ NETWORK SETTINGS ]
# These tests run before every remote transfer
# If you enable SSH tests, you will be prompted for the remote password twice until you copy the SSH key
icmp_test: true
ssh_test: false

# [ SSH KEYTOOL DEFAULTS ]
ssh_key_directory: /var/cargoport/keys
ssh_private_key_name: cargoport-id-ed25519

# [ LOGGING ]
# I'd recommend debug or info for most cases
log_level: info       # 'debug', 'info', 'warn', 'error', 'fatal'

# defines .log output type depending on taste
# json works well if you use jq with it
log_format: text        # 'json' or 'text'

# if 'text' format, logs will utilize ANSI codes for colouring
# great for readability, but makes casual log grepping harder without using looser matches
log_text_format_colouring: true

# [ METRICS ] 
metrics_dir: /var/cargoport/metrics
# If per_job_metrics_server is enabled, or cargoport -metrics-daemon is run
# Then the prometheus /metrics endpoint will be available via this address:port
listen_address: 127.0.0.1
listen_port: 9101
# Optionally allow cargoport to run an http metrics endpoint after each job run
# This endpoint is exposed for a defined number of seconds and can be scraped to monitor trends
per_job_metrics_server: false # open http /metrics endpoint after each job attempt
listen_duration: 60 # expose http endpoint for 60s after job
# Interval between metrics exposure reloads when running in headless metrics daemon mode
# Only applies when -metrics-daemon flag is passed
metrics_daemon_reload_interval: 30 