# [ LOCAL CARGOPORT DEFAULTS ]
## Cargoport Root Directory
## Please change default dir using -setup flag
default_cargoport_directory: %s

## Skip all local backups unless otherwise specified (-skip-local=false for local jobs)
skip_local_backups: false

# [ REMOTE CARGOPORT DEFAULTS]
## Default username and host to be used for '-remote-send-defaults' flag
## Default password cannot be set, please use SSH keys instead!
default_remote_user: admin
## Accepts any valid ipv4/6 address or hostname
default_remote_host: 10.0.0.1
#default_remote_output_dir: "/var/cargoport/remote/"