package util

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"filippo.io/age"
	"github.com/adrian-griffin/cargoport/logger"
)

// create age key pub/priv
func GenerateAgeKeypair(keyDirectory, keyName string) error {
	secretKeyPath := filepath.Join(keyDirectory, keyName)
	publicKeyPath := filepath.Join(keyDirectory, "cargoport-public.txt")

	// ensure age dir (e.g. /var/cargoport/keys/age) exists
	if err := os.MkdirAll(keyDirectory, 0700); err != nil {
		return fmt.Errorf("failed to create Age Key directory '%s': %v", keyDirectory, err)
	}

	// if the pub key already exists, do not overwrite
	if _, err := os.Stat(publicKeyPath); err == nil {
		logger.LogxWithFields("warn", fmt.Sprintf("Age encryption/public key '%s' already exists, to avoid creating duplicate identities, skipping generation", publicKeyPath), map[string]interface{}{
			"package": "agekeytool",
			"action":  "generate_keypair",
		})
		return nil
	}

	if _, err := os.Stat(secretKeyPath); err == nil {
		logger.LogxWithFields("warn", fmt.Sprintf("Age private key '%s' already exists, to avoid creating duplicate identities, skipping generation", secretKeyPath), map[string]interface{}{
			"package": "agekeytool",
			"action":  "generate_keypair",
		})
		return nil
	}

	// detect os/system hostname for use in key comment
	hostName, err := os.Hostname()
	if err != nil {
		return fmt.Errorf("failed to gather system hostname: %v", err)
	}

	// generate new keys
	id, err := age.GenerateX25519Identity()
	if err != nil {
		return fmt.Errorf("failed to generate age keys: %w", err)
	}
	recipKey := id.Recipient().String()

	// build custom private key header
	var privateHeaderText string
	privateHeaderText += fmt.Sprintf("# Cargoport age encryption private key\n")
	privateHeaderText += fmt.Sprintf("# Do not lose this file, it is your ONLY means for decrypting encrypted backups!\n")
	privateHeaderText += fmt.Sprintf("# This file or its contents should be copied or stored securely (offline machine, password manager)\n")
	privateHeaderText += fmt.Sprintf("# To minimize impact if an unauthorized user gains access to this machine, the private/decrypt key should be REMOVED from this\n")
	privateHeaderText += fmt.Sprintf("# \n")
	if hostName != "" {
		privateHeaderText += fmt.Sprintf("# Key generated by: %s\n", hostName)
	}
	privateHeaderText += fmt.Sprintf("# Created: %s\n", time.Now().UTC().Format(time.RFC3339))
	privateHeaderText += fmt.Sprintf("# Public Key/Encryption Key: %s\n", recipKey)
	privateHeaderText += fmt.Sprintf("# \n")
	privateHeaderText += id.String() + "\n"

	// write private key atomically, 0600
	if err := WriteFileAtomic(secretKeyPath, []byte(privateHeaderText), 0o600); err != nil {
		return fmt.Errorf("failed to write key file: %w", err)
	}

	// build custom public key header
	var publicHeaderText string
	publicHeaderText += fmt.Sprintf("# Cargoport age encryption/public key\n")
	publicHeaderText += fmt.Sprintf("# This key is cargoport's global encryption key. It can be shared.\n")
	publicHeaderText += fmt.Sprintf("# If you are using Cargoport on multiple machines, this key should be copied to each machine\n")
	publicHeaderText += fmt.Sprintf("# This key acts as your global Cargoport key, and should be reused on all cargoport machines\n")
	publicHeaderText += fmt.Sprintf("# \n")
	publicHeaderText += recipKey + "\n"

	// write public/encrytion key atomically, 0644
	if err := WriteFileAtomic(publicKeyPath, []byte(publicHeaderText), 0o644); err != nil {
		return fmt.Errorf("failed to write public file: %w", err)
	}

	// set private key to 600
	// if err := os.Chmod(secretKeyPath, 0600); err != nil {
	//	return fmt.Errorf("failed to chmod private key: %v", err)
	// }

	logger.LogxWithFields("info", fmt.Sprintf("Age key pair generated at: %s", keyDirectory), map[string]interface{}{
		"package": "agekeytool",
		"action":  "generate_keypair",
		"path":    keyDirectory,
	})
	return nil
}

// encrypt tarball and optionally remove unencrypted srcfile
func AgeEncrypt(recipientPath, rawTarGzPath string, removeRawSrc bool) (encryptGzPath string, err error) {
	// load recips
	recipients, err := LoadRecipientFile(recipientPath)
	if err != nil {
		return "", err
	}
	// if recips length is 0, err
	if len(recipients) == 0 {
		return "", fmt.Errorf("Age encryption/public key file at %s empty or unreadable", recipientPath)
	}

	// open tarball
	rawTarGz, err := os.Open(rawTarGzPath)
	if err != nil {
		return "", err
	}
	defer rawTarGz.Close()

	// build output paths
	encryptGzPath = rawTarGzPath + ".age"
	tmpEncGzPath := encryptGzPath + ".tmp"

	// os stat output dir prior to writing
	outputDirInfo, err := os.Stat(filepath.Dir(encryptGzPath))
	if err != nil {
		return "", fmt.Errorf("Unable to validate %v for encrypted backup output", encryptGzPath)
	}
	// check output dir perms
	stat, ok := outputDirInfo.Sys().(*syscall.Stat_t)
	if !ok {
		return encryptGzPath, fmt.Errorf("unable to read unix ownership info for %s", filepath.Dir(encryptGzPath))
	}
	//outputDirPerms := outputDirInfo.Mode().Perm()

	if stat.Uid != uint32(os.Geteuid()) {
		return encryptGzPath, fmt.Errorf("directory not owned by current user")
	}
	//if outputDirPerms&0o077 != 0 {
	//	return encryptGzPath, fmt.Errorf("insecure permissions on %s: %04o", filepath.Dir(encryptGzPath), outputDirPerms)
	//}

	// create temp output file (encrypted)
	tmpOutput, err := os.OpenFile(tmpEncGzPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return encryptGzPath, fmt.Errorf("Unable to create tempfile at %s", tmpEncGzPath)
	}

	// nuke tmp file if issues arise
	success := false
	defer func() {
		_ = tmpOutput.Close()
		if !success {
			_ = os.Remove(tmpEncGzPath)
		}
	}()

	// encrypt tarball using recipient key
	encryptedWriter, err := age.Encrypt(tmpOutput, recipients...)
	if err != nil {
		return encryptGzPath, fmt.Errorf("Failure to encrypt tarball using recipient key: %w", err)
	}

	// stream raw tar data through encryption out to temp file
	if _, err := io.Copy(encryptedWriter, rawTarGz); err != nil {
		// if fail, shut encrypted writer
		_ = encryptedWriter.Close()
		return encryptGzPath, fmt.Errorf("Failure to write encrypted tmpfile to %s: %w", tmpEncGzPath, err)
	}

	// after successful encrypt, shut encryption writer
	if err := encryptedWriter.Close(); err != nil {
		return encryptGzPath, fmt.Errorf("Failed to shut encryption process down: %w", err)
	}

	// sync and close tmpfile output
	if err := tmpOutput.Sync(); err != nil {
		return encryptGzPath, fmt.Errorf("Failed to sync output bytes post encryption: %w", err)
	}
	if err := tmpOutput.Close(); err != nil {
		return encryptGzPath, fmt.Errorf("Failed to close out tmpfile writing post encryption: %w", err)
	}

	// rename file atomically to non-tmp location
	if err := os.Rename(tmpEncGzPath, encryptGzPath); err != nil {
		return encryptGzPath, fmt.Errorf("failed to rename %q to %q: %w", tmpEncGzPath, encryptGzPath, err)
	}

	// optionally remove raw, unencrypted src file
	if removeRawSrc {
		if err := os.Remove(rawTarGzPath); err != nil {
			logger.LogxWithFields("warn", fmt.Sprintf("encrypted successfully, but failed to remove raw tarball: %v", err), map[string]interface{}{
				"package": "agekeytool",
				"action":  "encrypt_backup",
			})
		}
	}

	statInfo, err := os.Stat(encryptGzPath)
	if err != nil {
		return encryptGzPath, fmt.Errorf("failed to validate output encryption file path: %v", err)
	}

	logger.LogxWithFields("info", fmt.Sprintf("Successfully encrypted tarball"), map[string]interface{}{
		"package":    "agekeytool",
		"action":     "encrypt_backup",
		"size_bytes": statInfo.Size(),
	})

	success = true
	return encryptGzPath, nil
}

// load recipients file, ignores comments and linebreaks
func LoadRecipientFile(recipientsFilePath string) ([]age.Recipient, error) {
	recipsFile, err := os.Open(recipientsFilePath)
	if err != nil {
		return nil, fmt.Errorf("error loading encryption keys at %q: %w", recipientsFilePath, err)
	}
	defer recipsFile.Close()

	// read thru lines
	var loadedRecipients []age.Recipient
	scanner := bufio.NewScanner(recipsFile)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// actually parse key string into age key object
		recipientKey, err := age.ParseX25519Recipient(line)
		if err != nil {
			return nil, fmt.Errorf("failed to read encryption key from %s, line %d: %w", recipientsFilePath, lineNum, err)
		}

		// load each iteration into recipients object
		loadedRecipients = append(loadedRecipients, recipientKey)
	}

	// validations
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("issue reading encryption key file %s: %w", recipientsFilePath, err)
	}

	if len(loadedRecipients) == 0 {
		return nil, fmt.Errorf("no encryption keys found at %s", recipientsFilePath)
	}

	return loadedRecipients, nil

}
